-- Seed European dishes (20 each: Paris, Rome, Barcelona, Berlin).
-- Run after regions exist. Mirrors vault/techlead/03-build/005_seed_european_dishes.sql

-- ---------------------------------------------------------------------------
-- DISH SEED
-- ---------------------------------------------------------------------------
INSERT INTO public.dishes (slug, name_en, name_local) VALUES
-- Paris
('croissant', 'Croissant', 'Croissant'), ('baguette', 'Baguette', 'Baguette'), ('jambon-beurre', 'Jambon-Beurre', 'Jambon-Beurre'), ('quiche-lorraine', 'Quiche Lorraine', 'Quiche Lorraine'), ('escargots', 'Escargots', 'Escargots'), ('boeuf-bourguignon', 'Boeuf Bourguignon', 'Boeuf Bourguignon'), ('ratatouille', 'Ratatouille', 'Ratatouille'), ('onion-soup', 'Onion Soup', 'Soupe à l''oignon'), ('confit-de-canard', 'Confit de Canard', 'Confit de Canard'), ('macarons', 'Macarons', 'Macarons'), ('steak-frites', 'Steak Frites', 'Steak Frites'), ('sole-meuniere', 'Sole Meunière', 'Sole Meunière'), ('tartare-de-boeuf', 'Tartare de Bœuf', 'Tartare de Bœuf'), ('cassoulet', 'Cassoulet', 'Cassoulet'), ('poulet-roti', 'Poulet Rôti', 'Poulet Rôti'), ('hachis-parmentier', 'Hachis Parmentier', 'Hachis Parmentier'), ('tartiflette', 'Tartiflette', 'Tartiflette'), ('moules-marinieres', 'Moules Marinières', 'Moules Marinières'), ('salade-nicoise', 'Salade Niçoise', 'Salade Niçoise'), ('profiteroles', 'Profiteroles', 'Profiteroles'),
-- Rome
('carbonara', 'Spaghetti Carbonara', 'Spaghetti Carbonara'), ('cacio-e-pepe', 'Cacio e Pepe', 'Cacio e Pepe'), ('amatriciana', 'Amatriciana', 'Amatriciana'), ('pizza-margherita', 'Pizza Margherita', 'Pizza Margherita'), ('saltimbocca', 'Saltimbocca', 'Saltimbocca'), ('carciofi-alla-giudia', 'Carciofi alla Giudia', 'Carciofi alla Giudia'), ('suppli', 'Suppli', 'Suppli'), ('coda-alla-vaccinara', 'Coda alla Vaccinara', 'Coda alla Vaccinara'), ('pizza-bianca', 'Pizza Bianca', 'Pizza Bianca'), ('porchetta', 'Porchetta', 'Porchetta'), ('gnocchi', 'Gnocchi', 'Gnocchi'), ('risotto-funghi', 'Risotto ai Funghi', 'Risotto ai Funghi'), ('ossobuco', 'Ossobuco', 'Ossobuco'), ('polenta', 'Polenta', 'Polenta'), ('pappa-al-pomodoro', 'Pappa al Pomodoro', 'Pappa al Pomodoro'), ('ribollita', 'Ribollita', 'Ribollita'), ('bistecca-fiorentina', 'Bistecca alla Fiorentina', 'Bistecca alla Fiorentina'), ('lasagna', 'Lasagna', 'Lasagna'), ('tiramisu', 'Tiramisu', 'Tiramisu'), ('gelato', 'Gelato', 'Gelato'),
-- Barcelona
('paella-valenciana', 'Paella Valenciana', 'Paella Valenciana'), ('fideua', 'Fideuà', 'Fideuà'), ('escalivada', 'Escalivada', 'Escalivada'), ('pa-amb-tomaquet', 'Pa amb Tomàquet', 'Pa amb Tomàquet'), ('botifarra-mongetes', 'Botifarra amb Mongetes', 'Botifarra amb Mongetes'), ('calcots', 'Calçots', 'Calçots'), ('crema-catalana', 'Crema Catalana', 'Crema Catalana'), ('bombas', 'Bombas', 'Bombas'), ('esqueixada', 'Esqueixada', 'Esqueixada'), ('suquet-de-peix', 'Suquet de Peix', 'Suquet de Peix'), ('tortilla-patatas', 'Tortilla de Patatas', 'Tortilla de Patatas'), ('patatas-bravas', 'Patatas Bravas', 'Patatas Bravas'), ('croquetas', 'Croquetas', 'Croquetas'), ('gambas-ajillo', 'Gambas al Ajillo', 'Gambas al Ajillo'), ('jamon-iberico', 'Jamón Ibérico', 'Jamón Ibérico'), ('chorizo-vino', 'Chorizo al Vino', 'Chorizo al Vino'), ('pulpo-gallega', 'Pulpo a la Gallega', 'Pulpo a la Gallega'), ('gazpacho', 'Gazpacho', 'Gazpacho'), ('salmorejo', 'Salmorejo', 'Salmorejo'), ('pimientos-padron', 'Pimientos de Padrón', 'Pimientos de Padrón'),
-- Berlin
('currywurst', 'Currywurst', 'Currywurst'), ('doner-kebab', 'Döner Kebab', 'Döner Kebab'), ('koenigsberger-klopse', 'Königsberger Klopse', 'Königsberger Klopse'), ('eisbein', 'Eisbein', 'Eisbein'), ('schnitzel', 'Schnitzel', 'Schnitzel'), ('spaetzle', 'Spätzle', 'Spätzle'), ('sauerbraten', 'Sauerbraten', 'Sauerbraten'), ('rouladen', 'Rouladen', 'Rouladen'), ('bratwurst', 'Bratwurst', 'Bratwurst'), ('weisswurst', 'Weisswurst', 'Weisswurst'), ('leberkase', 'Leberkäse', 'Leberkäse'), ('kartoffelsalat', 'Kartoffelsalat', 'Kartoffelsalat'), ('rotkohl', 'Rotkohl', 'Rotkohl'), ('sauerkraut', 'Sauerkraut', 'Sauerkraut'), ('brezel', 'Brezel', 'Brezel'), ('schwarzbrot', 'Schwarzbrot', 'Schwarzbrot'), ('apfelstrudel', 'Apfelstrudel', 'Apfelstrudel'), ('kaiserschmarrn', 'Kaiserschmarrn', 'Kaiserschmarrn'), ('berliner', 'Berliner Pfannkuchen', 'Berliner Pfannkuchen'), ('schwarzwaelder-kirschtorte', 'Schwarzwälder Kirschtorte', 'Schwarzwälder Kirschtorte')
ON CONFLICT (slug) DO NOTHING;

-- ---------------------------------------------------------------------------
-- REGION ↔ DISH (region_id + dish_id; prevalence per CHECK constraint)
-- ---------------------------------------------------------------------------
INSERT INTO public.region_dish_mapping (region_id, dish_id, prevalence)
SELECT r.id, d.id, 'COMMON'::text
FROM (VALUES
  ('paris', 'croissant'), ('paris', 'baguette'), ('paris', 'jambon-beurre'), ('paris', 'quiche-lorraine'), ('paris', 'escargots'), ('paris', 'boeuf-bourguignon'), ('paris', 'ratatouille'), ('paris', 'onion-soup'), ('paris', 'confit-de-canard'), ('paris', 'macarons'), ('paris', 'steak-frites'), ('paris', 'sole-meuniere'), ('paris', 'tartare-de-boeuf'), ('paris', 'cassoulet'), ('paris', 'poulet-roti'), ('paris', 'hachis-parmentier'), ('paris', 'tartiflette'), ('paris', 'moules-marinieres'), ('paris', 'salade-nicoise'), ('paris', 'profiteroles'),
  ('rome', 'carbonara'), ('rome', 'cacio-e-pepe'), ('rome', 'amatriciana'), ('rome', 'pizza-margherita'), ('rome', 'saltimbocca'), ('rome', 'carciofi-alla-giudia'), ('rome', 'suppli'), ('rome', 'coda-alla-vaccinara'), ('rome', 'pizza-bianca'), ('rome', 'porchetta'), ('rome', 'gnocchi'), ('rome', 'risotto-funghi'), ('rome', 'ossobuco'), ('rome', 'polenta'), ('rome', 'pappa-al-pomodoro'), ('rome', 'ribollita'), ('rome', 'bistecca-fiorentina'), ('rome', 'lasagna'), ('rome', 'tiramisu'), ('rome', 'gelato'),
  ('barcelona', 'paella-valenciana'), ('barcelona', 'fideua'), ('barcelona', 'escalivada'), ('barcelona', 'pa-amb-tomaquet'), ('barcelona', 'botifarra-mongetes'), ('barcelona', 'calcots'), ('barcelona', 'crema-catalana'), ('barcelona', 'bombas'), ('barcelona', 'esqueixada'), ('barcelona', 'suquet-de-peix'), ('barcelona', 'tortilla-patatas'), ('barcelona', 'patatas-bravas'), ('barcelona', 'croquetas'), ('barcelona', 'gambas-ajillo'), ('barcelona', 'jamon-iberico'), ('barcelona', 'chorizo-vino'), ('barcelona', 'pulpo-gallega'), ('barcelona', 'gazpacho'), ('barcelona', 'salmorejo'), ('barcelona', 'pimientos-padron'),
  ('berlin', 'currywurst'), ('berlin', 'doner-kebab'), ('berlin', 'koenigsberger-klopse'), ('berlin', 'eisbein'), ('berlin', 'schnitzel'), ('berlin', 'spaetzle'), ('berlin', 'sauerbraten'), ('berlin', 'rouladen'), ('berlin', 'bratwurst'), ('berlin', 'weisswurst'), ('berlin', 'leberkase'), ('berlin', 'kartoffelsalat'), ('berlin', 'rotkohl'), ('berlin', 'sauerkraut'), ('berlin', 'brezel'), ('berlin', 'schwarzbrot'), ('berlin', 'apfelstrudel'), ('berlin', 'kaiserschmarrn'), ('berlin', 'berliner'), ('berlin', 'schwarzwaelder-kirschtorte')
) AS v(region_slug, dish_slug)
JOIN public.regions r ON r.slug = v.region_slug
JOIN public.dishes d ON d.slug = v.dish_slug
ON CONFLICT (region_id, dish_id) DO NOTHING;
